imports:
    - { resource: config.yml }
    - { resource: security.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

fos_google:
    client_id: 217588854210-2p5fnc9epnkqeiusvtr6q6illgsho6e6.apps.googleusercontent.com
    client_secret: Os9np78mE1kZnzju_QeXjBNF
    redirect_uri: http://meedule.abmundi.com/login_check