security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/admin
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
