<?php

namespace Meedule\MeetingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends EntityRepository
{
    
    public function findByAttendee($id, $email){
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT m FROM MeeduleMeetingBundle:Meeting m
                JOIN m.attendees a
                WHERE (a.user = :id
                OR a.mail LIKE :mail)
                AND m.date >= :date
                ORDER BY m.date ASC')
             ->setParameters(array(
                 'id'=> $id,
                 'mail' => $email,
                 'date' => new \DateTime
             ));
        return $query->getResult();
    }
}