<?php

namespace Meedule\MeetingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
    public function getTopicsByMeeting($meeting) {
        $qb = $this->createQueryBuilder('t');
        return $qb
                ->where('t.meeting = :id')
                ->orderBy('t.position', 'ASC')
                ->setParameter('id', $meeting->getId());
    }
    
}